%import common.WS
%import common.CPP_COMMENT
%import common.WS_INLINE
%import common.NEWLINE
%import common.SIGNED_NUMBER -> NUMBER

%ignore WS
%ignore WS_INLINE
%ignore CPP_COMMENT

start: section

section: "Data:" NEWLINE? declaration+

date_expr: date_literal | "Latest" | "Earliest"
date_identifier: /(?i)StartDate/ | /(?i)EndDate/
declaration: date_declaration | normal_declaration
date_declaration: date_identifier ":" _TAB? date_expr NEWLINE?
normal_declaration: identifier ":" _TAB? expression NEWLINE?
expression: logical_expr format_spec? CPP_COMMENT?
format_spec: /\{%[^}]*\}/
logical_expr: comparison_expr (logical_op comparison_expr)*
logical_op: "and" | "or"
comparison_expr: add_expr (comparison_op add_expr)*
add_expr: mul_expr (add_op mul_expr)*
mul_expr: indexed_expr (mul_op indexed_expr)*
mul_op: "*" | "/"
add_op: "+" | "-"
indexed_expr: primary ("[" NUMBER "]")?
primary: "(" expression ")" | base_expr
base_expr: function_call | identifier | NUMBER | string_literal | stock_symbol | field_list | path_name 
date_literal: /\d{8}|\d{4}\/\d{2}\/\d{2}|\d{4}-\d{2}-\d{2}|\d{4}\.\d{2}\.\d{2}|\d{2}-[A-Za-z]{3}-\d{2,4}|\d{1,2}\/\d{1,2}\/\d{2,4}|\d{1,2}-\d{1,2}-\d{2,4}|\d{1,2}\.\d{1,2}\.\d{2,4}/
path_name: reserved_word path_literal? | path_literal
reserved_word: /\?[a-z]+\?/
path_literal: /[^\s?]+/
field_list: field_item? ("," field_item? )*
field_item: identifier | null_value
null_value:
comparison_op: "<" | ">" | "<=" | ">=" | "==" | "<>" | "!=" | "=" 
function_call: identifier "(" arguments? ")"
arguments: expression ("," expression)*
identifier: /[a-zA-Z_][a-zA-Z0-9_]*/
string_literal: /\$\w+/
stock_symbol: /\$\$[A-Z_][A-Z0-9_]*/

_TAB: /\t/
